### ISSUE TITLE
mhi-first and mhi-last don't have the same resolution (on paper yes, but look at the image!)

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#102]
We are maybe setting the matrix dim when reading a video too late, so on the first frame it probably just scales a low resolution image to a too big dim. Something something.

**Comment by balintlaczko** [comment]
This is a bit mysterious. It still happens sometimes with one video, all the rest seems to be fine.

**Comment by aleksati** [comment]
Same on Mac

**Comment by balintlaczko** [comment]
You mean same resolution or same problem?

**Comment by balintlaczko** [comment]
moving the issue [here](https://github.com/fourMs/VideoAnalysis/issues/23)
