### ISSUE TITLE
Collect all settings in log.txt

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#107]
Since we already save cropping, skipping and trimming data to the log, should we also save color, box threshold, and noise reduction type? One could argue that they are all settings that affect the exported results and would, therefore, qualify as relevant analysis data.

**Comment by balintlaczko** [comment]
Yes, I fully agree! Let's do it! I guess since we already have the string-formatted ("on"/"off") settings in VA_items, we might as well just extract it from there and put it into the log.
