### ISSUE TITLE
Export jpegs and pngs only

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#11]
as for the tiff: they get called first, then the jpeg saves, I suspect maybe there is a scheduling or I/O issue.
as for the jxf: it's not implemented, although the log file claims it should be there. Should we implement it?

**Comment by balintlaczko** [comment]
NB: in many cases the tiff is also not implemented.

**Comment by alexarje** [comment]
You can just delete the TIFF and JXF export functionality, I think. I added these because there were some issues with JPEG export in some version of Max. Is it possible to export uncompressed PNG now? That may be an interesting extra option, in addition to the compressed JPEG files.

**Comment by balintlaczko** [comment]
OK, will test that!

**Comment by alexarje** [comment]
If PNG is not supported, we may want to allow for both uncompressed TIFF and compressed JPEG.

**Comment by AleksanderTidemann** [comment]
I´ve changed all the TIFF formats to PNG now for testing on windows. PNG has actually become the default image-exporting format for the jit.matrices. However, with 8-bit compression. So I have two questions:

* Is there any reason why some files are exported as TIFF/PNG and others in JPEG?

* Would it be useful to have an option in the UI for choosing which format to export the images in? That way, the user can decide whether to export the images in lossless TIFF, compressed PNG, and/or JPEG.

**Comment by aleksati** [comment]
A user can now choose between JPEG, TIFF, and PNG-8. JPEG is the default. This should be further implemented in the Appstyle menubare, later.
