### ISSUE TITLE
Make App-style menu bar for options and actions

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#13]

**Comment by alexarje** [comment]
Yes, good idea! The main point is to make it as user-friendly as possible. I want a random music student with no knowledge about the field to just open a video file, click a button, and get out usable files!

**Comment by aleksati** [comment]
In that case, having a basic how-to guide would be nice to include in the menu bar, as well as all the documentation in an "about" section.

**Comment by alexarje** [comment]
Yes, good idea.

**Comment by balintlaczko** [comment]
So far things to put in the app menu:
-use same cropping for all files in a folder
-remember cropping settings for each file in a folder
-maybe the color options could also go here? Since it's probably not used so often to have it on the main UI. (or is it?)
-checkboxes for: export JPEG, TIFF, PNG.
-save/load settings from file

will extend the list here just to remember.

**Comment by balintlaczko** [comment]
Done!
I guess there will be future issues about this, but now that it is there I think we should start thinking about what we can move from the main UI to the menubar, and of course what other only-menubar options should we add.

**Comment by aleksati** [comment]
Cool! As we discussed over, an "about" section with all the documentation and a quick "how-to-use" section might be nice include there. That way, the user doesn't have to access the GitHub page to get info on how to use the app. Even if UI is very intuitive, this would make it fool-proof.

Also, I was thinking maybe the export-boxes could be in the menubar. Any thoughts on that?

**Comment by balintlaczko** [comment]
Yes, good idea! The export boxes are already implemented in the current version, I was actually thinking maybe we can remove them from the UI.
And also yes, the documentation is actually one of the initial issues we can now finally implement. My idea is to make a dedicated menu item for that, as far as I know the *About* is typically just a little "card" with some license and contact info. But I had some issues when I tried to put another menu item under *About*, but haven't tried much, so maybe it's possible somehow.

I will make an issue for the documentation patch now.
