### ISSUE TITLE
Add skipframe functionality

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#15]

**Comment by aleksati** [comment]
Was this initially meant only as a functionality for the motiongrams, or for the entire output?

**Comment by balintlaczko** [comment]
I am not sure actually, but my idea is that maybe it would be useful to implement it for the source video playback (both framedump-style and online playback) - so then if you load a video of the 9-hour train ride from Bergen to Oslo (lol :D) you can for example skip 29 frames so you only get 1 frame / sec - or something like that... But I think it's definitely needed for the offline framedump, and it's a question if it's also necessary online.

**Comment by aleksati** [comment]
I see, yeah that would be nice! I'm sorry, but I´m not quite sure I get what you mean by "offline" and "online" playback in this context?

**Comment by alexarje** [comment]
Offline is the framedump (non-realtime) version. The realtime version will skip frames anyway if it cannot keep up to speed.

**Comment by aleksati** [comment]
I have an idea of a skipframe function but don’t know if I´m on the right track here. Could this be implemented between the [jit.qt.movie] and [jit.broca] using a [jit.matrixset] configuration to effectively record and output the wanted indexes? It would then use the framedump as input values. 

I´ve uploaded a basic demo on this to Balints repo called «Frameskip_quickdemo_aleks.maxpat.», which shows very quickly how such a functionality could be made. I don't think it is very optimal, but with some work, I think it could do the job. Presuming of course, that I have understood this correctly.

Is this something worth pursuing further? I guess there are many ways of tackling this.

**Comment by alexarje** [comment]
I am my linux computer now, so cannot check your patch. But there is actually a skipframe function in the framedump message you can send to jit.qt.movie. If you send "framedump 4" for example it will skip 4 frames. Would be nice to let the user know how large the final motiongram should be. Then you will need to get the number of frames in the video, and then calculate the width/height in pixels based on the number of skipped frames.

**Comment by AleksanderTidemann** [comment]
I see, yes this is quite different than what I did. 
Thanks! I´ll look into it.

**Comment by aleksati** [comment]
I see, hadn't noticed that! Yes, that would probably be a better approach.
Thanks, I´ll look into this and the preview of the final motiongram size.

**Comment by aleksati** [comment]
I made it so the motiongram dimensions correspond to the videos' original parameters at first, but are re-calibrated based on the cropping. The other way is to bypass the cropping completely and make the motiongrams fixed to the videos' original dimension.

**Comment by aleksati** [comment]
This is implemented. Will commit later with @balintlaczko .
