### ISSUE TITLE
Make all [send]-s, [receive]-s and [value]-s local

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#18]
To avoid potential interference from other opened patches.

**Comment by alexarje** [comment]
Yes, good point!

**Comment by balintlaczko** [comment]
Before we do anything about this we should check whether the standalone actually creates a separate Max environment, which would solve this issue automatically.

**Comment by balintlaczko** [comment]
It is all local in the build, since that creates its own Max env.
