### ISSUE TITLE
Why do we always want to see the first frame when cropping?

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#19]

**Comment by alexarje** [comment]
Could also pick a frame some seconds into the video? Or are you thinking about running the video? That would be more CPU-intensive, I think.

**Comment by balintlaczko** [comment]
If we always want to crop before we start the playback, I understand. I had this experience when I tested it with videos in which the valuable movement begins a bit after the start (for example after I minnimize OBS and bring the window in front where the stuff happens) and it was hard to crop to that while having to see the first frame. What I propose is just to always crop on the frame which is shown currently. This would effectively mean just disabling a "loopback" bang in the current patch.

**Comment by alexarje** [comment]
Yes, that makes sense. Good idea.

**Comment by balintlaczko** [comment]
Fixed - commit comes later together with @AleksanderTidemann

**Comment by alexarje** [comment]
Great!
