### ISSUE TITLE
Shouldn't we render the 3 output streams into an external [jit.window] instead?

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#24]
It would maybe enhance CPU efficiency, make the rendered window re-sizable, and keep the top-level patch's Y dim (- it looks suspicious when for ex. going out from a small cropped state to non-cropped suddenly we don't see half of the picture).

**Comment by alexarje** [comment]
Yes, it could possibly be shown in a jit.window instead. Just need to find a location for where to put the settings? Perhaps you can talk to @alenaclim about the usability. She took the course MUS2006 which this program was originally developed for.

**Comment by balintlaczko** [comment]
Okay, yes, then we discuss it with Alena! My idea is to keep the settings in the max patch, (even with the cropping display in it) and have the glued triple image in the jit.window. If we go for the openGL thing, I also thought about having the settings on collapsible overlays - but maybe that would clutter things too much... We will see how it makes the best sense.

**Comment by alexarje** [comment]
Yes, do whatever you think makes sense.

**Comment by alenaclim** [comment]
I think indeed it would be better to try it on a jit.window. I'll discuss it with Balint further ^.^

**Comment by balintlaczko** [comment]
Implemented - commit comes later together with @AleksanderTidemann

**Comment by alexarje** [comment]
Nice
