### ISSUE TITLE
Make user option for which final matrices to see (instead of always having all three)

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#25]

**Comment by alexarje** [comment]
Not sure I understand the question. The output are individual files?

**Comment by balintlaczko** [comment]
No, I was just thinking maybe we don't always want to see all outputs (box, motion, motion history) at once in the final (glued) matrix. It could be an option for the user with some checkboxes to decide which of those matrices should be "active" - just a thought.

**Comment by alexarje** [comment]
Ah, I see. Yes, that is a good idea.

**Comment by aleksati** [comment]
It is possible to replace the [jit.clue..] with a [jit.gen gate] and a [live.tab]. I´ve done this in the «VideoAnalysis_balint_dev» now to show. This allows users to choose between which 3 matrices to view during playback.

**Comment by balintlaczko** [comment]
Implemented the checkbox-style options for each. Also had to make the [autosize%] a little overhaul to prevent it from drawing very wide windows at extreme cropped aspect ratios, and to resize contents based on how many columns are rendered.
(commit comes later when together with @AleksanderTidemann)

**Comment by alexarje** [comment]
Yes, very nice to have some checking for extreme values to avoid issues.
