### ISSUE TITLE
Should we try to move everything into OpenGL?

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#26]
This would be a long-term aim after we get things run properly in its current state.
Right now on my (old) laptop the user experience is quite bad because everything is done on the CPU, and there are a lot of matrices to calculate, so I get very poor frame rates, and Max gets very much bogged down completely when the video is running...
If we could manage to change all (or most) of the jit.processes into their jit.gl.equivalents then all the stuff could run on the GPU and it would be a looooot smoother - I think. And for most of the stuff it would not even be too hard to convert. The only things I am not sure about at the moment are the cv.jit.stuff and the xray.stuff, but I think even if those would stay as they are we would get a major speed upgrade overall...

**Comment by alexarje** [comment]
Yes, that would be an interesting enhancement. I made the patch before OpenGL was introduced in Jitter...

**Comment by balintlaczko** [comment]
The more I use this with big videos the more pressing this issue seems to be.

**Comment by alexarje** [comment]
Yes, good point. We just need to check whether this would cause issues with people on low-spec'ed computers without dedicated graphics cards.

**Comment by balintlaczko** [comment]
this became a duplicate of [this](https://github.com/fourMs/VideoAnalysis/issues/13) issue, closing it here
