### ISSUE TITLE
ICNS and ICO files for application icon. 

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#28]
It would be nice to have a RITMO icon for the application. Do you have access to a RITMO image in ICNS and ICO format Alexander, or should we perhaps make them?

**Comment by alexarje** [comment]
Yes, that is a great idea. I'll send you the image files on e-mail. We don't have ICO format files, so great if you can make it.

**Comment by aleksati** [comment]
Both ICNS and ICO is now implemented and added to the Repo.
