### ISSUE TITLE
The motiongrams (and possibly other files) are rendered incomplete?

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#29]
For example, the exported horizontal motiongrams tend to leave blank half of the print happening on the x-axis (the axis which corresponds to the framecount), despite the dimensions and general programming seeming correct. The same goes for the vertical. Might be due to an unfortunate signal delay in the system somewhere? Might be something else though.

Could you give a look, Balint?

**Comment by aleksati** [comment]
Based on how the images look, the problem should be with the [dstdimstart] printing. But the code seems legit.

**Comment by aleksati** [comment]
I´ve identified that the problem lies with the frame-dumped output of the [jit.qt.movie]. By attaching a simple counter to the main [jit.qt.movie] output, I discovered that the output count is always significantly less than the total amount of frames of the video. Hence the incomplete-ness of the rendered files. These should correspond to enable correct motiongram printing and further analysis "down the line". Might be due to the size and CPU load of the patch?

**Comment by balintlaczko** [comment]
Could be that the [jit.qt.movie] has a fix FPS (like 30) by default regardless of the source video's FPS? Something something...

**Comment by aleksati** [comment]
i`ll check

**Comment by aleksati** [comment]
Jupp, part of the problem was the @unique attribute. When disabled it outputted the right amount of frames. But there´s one final problem now with the jit.op absdiff object in the [mgt.motion%]. It also messes with the fame output (naturally), affecting the motiongram print. I will look more into it later

**Comment by alexarje** [comment]
Yes, the @unique attribute will lead to not all frames being output. This is good when doing realtime stuff, but not so good when using framedump.

**Comment by aleksati** [comment]
I had to make some changes to the [mgt.motion%] to enable the absdiff to output the correct fps without causing every other frame to be blank (zero). But this is now fixed and looking good. The commit will come later.

**Comment by aleksati** [comment]
The motiongrams are now good. Issues with other files-exports are attended to in other issues.
