### ISSUE TITLE
Cropping display aspect ratio should match source video's

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#31]

**Comment by alexarje** [comment]
Not sure if I understand what you mean here. I think it should be possible to crop to any ratio. Sometimes you may want to crop out only a certain part of the image, f.ex. one standing person.

**Comment by balintlaczko** [comment]
Yes, the cropping is free, I only meant that the pwindow itself should be autosized to match the input file's ascept.
For example I recorded something on my 1600x900 screen, and the 320x240 cropping display (the pwindow) squishes horizontally the image of that video. NB the aspect ratio is good now in the glued jit. window, so we only need to fix the cropping display (and perhaps the playbar beneath that with a little js kungfu)

**Comment by balintlaczko** [comment]
+1 idea: instead of resizing the pwindow and the playbar, just fix it with @usedstdim so if there is a 16:9 video there are some black bars on the top and bottom like in other video-editing software.

**Comment by alexarje** [comment]
Yes, good point!
