### ISSUE TITLE
Next video in folder (or new video) should switch off cropping and set crop dim to source dim

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#35]

**Comment by alexarje** [comment]
I guess this could be an option? Sometimes we do many similar shots of the same setup, and then it can actually be useful to keep the same cropping between videos.

**Comment by balintlaczko** [comment]
Good idea! This can be something in the menu system, I think.

**Comment by aleksati** [comment]
Oh, I didn't see this. I now pushed a version that switches off the cropping-button when a new file or folder is added. But we can easily make this an option in the menu, instead. (+ crop value reset)

**Comment by balintlaczko** [comment]
I think that's fine, I will add a menu checkbox for this. I think it is good if it resets as a default behavior with an option not to reset.
I was also thinking maybe there can be an automatic warning/popup message letting you know about the option (with a "don't show again" checkbox) when you open a folder - since I believe that's the typical scenario when we want to keep the cropping from file to file.

**Comment by aleksati** [comment]
Yes! Also, I noticed that this important when batch-exporting (exporting a folder of videos). In this case, the option should also make so that none of the motiongram, cropping or skipframe-settings reset when adding a new file.

**Comment by balintlaczko** [comment]
Btw just re-realised that there is already a coll memory implemented for remembering the crop dimensions of each file in a loaded folder (see [crop-stuff]). But I also notice on the implementation that it mistakenly overwrites the settings with the dim of the last cropping rectangle drawn with the mouse. Could be a cool option to remember the cropping box per item though - with keeping the other option of having the same cropping settings for each file in a folder, so I will open a separate issue for this.

**Comment by aleksati** [comment]
This is directly related to issue #39 . The crop rect now jumps back to source dim when the next video in the folder is selected IF no prior cropping has been drawn for that video. 

Closing this issue now.
