### ISSUE TITLE
Save/load all settings from files

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#46]
This is a cool addition we talked about on the meeting. I suppose we put the save/load settings thing into the menu bar.

**Comment by AleksanderTidemann** [comment]
By settings, do we mean all settings? Like color, threshold value, crop, export selection, etc.

**Comment by aleksati** [comment]
Involves saving and recalling:

* skip frame value
* trimming control (a yet non-existent feature, see issue #54 for more info)
* noise settings
* cropping option for each file (on/off)
* The various export options
* Colour settings

**Comment by balintlaczko** [comment]
Let's do this by extending the [dict VA_items] - currently only in [VA_cropping_data]. The cropping part is now implemented, we just have to add what we want.

**Comment by aleksati** [comment]
I see. Very nice! The dict is very elegant

**Comment by aleksati** [comment]
If you don´t mind, @balintlaczko . I would like to try to implement the saving and recalling of noise settings (Thresh, Type, and Box thresh) and color settings before we meet on Thursday.

**Comment by balintlaczko** [comment]
Great, go ahead!

**Comment by AleksanderTidemann** [comment]
One question; the way you implemented the [dict VA_items] now for the cropping. Can we store other info in the same dict? It seems to me that in the [VA_cropping_data] some of the scheduling is based on IF there is ANY info about a video in the [dict], then do something specific with the cropping. Will it then be okay if we store other video info in the same dict, or will it bug with the cropping info?

**Comment by AleksanderTidemann** [comment]
This in particular
![Skjermbilde 2020-02-09 kl  17 20 33](https://user-images.githubusercontent.com/54307488/74105721-a37c5700-4b60-11ea-8d3d-04cc2f65e6f0.png)

**Comment by balintlaczko** [comment]
Of course, I would ask you to implement it in VA_items. In the cropping we save the cropping state and cropping rect for each item. The same way (in other places) you can store the skipframe value or noise threshold for the same item. For inspiration you can take a look at the right side of the [VA_cropping_data] where the cropping states and cropping rectangles get saved. The algorithm in the cropping data is only looking for the cropping state and the cropping value (and if an entry exists at all), it won't care about anything else.

**Comment by aleksati** [comment]
Jupp! Figured it out just after I wrote the comments, actually. lol. Ill make some abstractions for the noise/box, file-format and skipframe based on the logic in VA_cropping_data.
