### ISSUE TITLE
"Noise Reduction" toggle should decide noise reduction, not the actual n.r. value

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#49]

**Comment by balintlaczko** [comment]
Or maybe it would be even nicer to make it dependent on the toggle and not the actual threshold value. This is actually a bug, since the toggle only hides the UI elements, otherwise everything depends on the thresh value being higher than 0. LOL. Will fix this now.

**Comment by aleksati** [comment]
Yes, and the amount of noise reduction (threshold value from 0 - 1 in float), does have a lot of effect on the export files. Maybe a multislider or a dial would be nice for usability here, instead of the float value box?

**Comment by balintlaczko** [comment]
I don't know, I think it's simpler to just see the number box, but you go ahead if you think it's nicer for the users!
