### ISSUE TITLE
Check if app is char-only

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#52]
For this check if:
- [jit.qt.movie] can output other than char format matrices
- there are any points in the patch where we convert to char
- everything can export from non-char matrices as well (- only if we find that other types are real possibilities)

**Comment by balintlaczko** [comment]
NB if we find out that our output matrices are char types in any case, we should revisit the question whether the png (or the jpeg) export actually compresses the image or not.

**Comment by aleksati** [comment]
All Char so far. tested 10 different videos.  Will continue on :)
