### ISSUE TITLE
[cv.jit.mean] sometimes creates artifacts over the image

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#53]
Sometimes they are just some dead cells, sometimes a diagonal white line through the pic, considerable part of the pic is dropped - and sometimes everything is fine. Can only be reset with restarting the patch. (Delete object + undo doesn't seem to fix it.) I think this could be a reason for the artifacts we observed previously in #36 
Tested on windows.

**Comment by balintlaczko** [comment]
Delete + retype manually also fixes it.

**Comment by aleksati** [comment]
Yes! I know what you mean. I´ve had the same experiences here, but less after we implemented the [jit.op (at)op + pass pass pass (at)Val 255] to the avg and mavg.

**Comment by balintlaczko** [comment]
I archive this now, since haven't happened for a while... Could be that we "accidentally" fixed it (ie. avoided doing the thing which triggers it). Could be that I close the issue and the bug immediately returns. :)
