### ISSUE TITLE
Make embedded documentation

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#55]
It would be nice to be able to get help already from the program let's say with accessing a menu item (like "Help", or "Get Started", etc). The options coming to my mind are:
- pdf of md file opening in browser
- the md file could actually be just a link to the readme on the github repo
- html file opening in browser
- html embedded in a patch
- patches (possibly including several bpatchers, maybe jwebs)

The list sort of goes from fastest to nicest...

For this task it would also be nice to be able to load gif files in embedded in a patch somehow (for little animated snippets). Without trying anything before I just list some options from the top of my head:
- fpic
- jweb (via html)
- jit.pwindow (via jit.movie or jit.matrixset or anything which can handle gifs most conveniently)

**Comment by aleksati** [comment]
Yes, a pdf of md in a "GetStarted" option would be nice. It could be the same, or similar, to the one we make for the GitHub page. It should be easily accessible, and maybe also with gif´s?

**Comment by balintlaczko** [comment]
OK, I guess it would be nice to have it in the github readme file too, so I will try to make something which embeds that (or something like that) in the patch!

**Comment by balintlaczko** [comment]
Ok so this works nicely now, though sadly the `video` html tag doesn't work in `[jweb]` but there is a good-enough workaround with gifs and pngs. It will be extended, styled, etc, but at least there is a technical framework now for the implementation.

**Comment by balintlaczko** [comment]
Updated the embedded documentation, should be enough to start. Can be extended in the future. :)
