### ISSUE TITLE
Export spreadsheets in .csv? 

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#56]
Additionally, by using a combination of commas and backlashes we can get spreadsheets complete with nice rows and columns. These would also be "import-friendly" to any other spreadsheet software/program.

Unless there are other reasons to keep using .text, of course.

**Comment by AleksanderTidemann** [comment]
Makes a real difference. 
 
![Skjermbilde 2020-01-07 kl  11 37 17](https://user-images.githubusercontent.com/54307488/71889369-47c64480-3142-11ea-968d-87b618336f9b.png)

**Comment by aleksati** [comment]
Like so. Now it's possible to actually read the stats after exporting. Will commit together with Balint in January.

![Skjermbilde 2020-01-07 kl  11 41 17](https://user-images.githubusercontent.com/54307488/71889589-bf946f00-3142-11ea-891f-5eb2d3bf74ba.png)

**Comment by balintlaczko** [comment]
Looks super cool!

**Comment by aleksati** [comment]
This is implemented and working.
