### ISSUE TITLE
Recall fps for each movie at [jit.qt.rec]

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#65]

**Comment by AleksanderTidemann** [comment]
All of a sudden, the jpeg codec in the jit.record is seriously bugging. By changing it to prores (4444, 422 or 244), it works. Tried with an additional [jit.matrix] and even [jit.vcr]. Even the help patch bugs with Jpeg codec. Video engine doesn't seem to matter.

Can you test this on Windows, @balintlaczko ? 

By the way, according to the old and new Max reference webpages on jit.rec, it seems that there was much more functionality to the object in the past. More codecs and customizability.

**Comment by aleksati** [comment]
All of a sudden, the jpeg codec in the jit.record is seriously bugging. By changing it to something like Apples prores, it works. Tried with an additional [jit.matrix] and even [jit.vcr]. Even the help patch bugs with Jpeg codec. Video engine doesn't seem to matter.

Can you test this on Windows, @balintlaczko ? Might just be a Mac thing

**Comment by balintlaczko** [comment]
I will, yes! What do you mean "it bugs"? Artifacts, like in the case of [cv.jit.mean]? Color/dim problems? Missing frames? I can work on this tomorrow, now I only had time to quickly check the helpfile of [jit.record], that works fine for me both on 30 FPS and 10, and both with h264 and jpeg. I am on VIDDLL. Does the problem occur when you use an FPS different from 30? Or is it there all the time?

**Comment by aleksati** [comment]
Yes, it occurs with any framerate. Both fixed and not. And on all three video prints. Consistent. The bugs are not like jit.mean. Many green frames all over the print and in between the video frames, as well as rapid and lagging video-content. Like back and forth jolts.

**Comment by aleksati** [comment]
I´ve sent you an email with a video of how it looks on my screen. Maybe you´ve encountered it before and know what it is.

Strangely, when I tried to convert the video to gif to send it here, the bugging got "fixed". By the online converter. Might be more evidence that this is something local with my mac or software. Therefore, I wish to try this on other macs before we do anything else.

In the meantime, I've pushed an integrated recall video fps function to the mg.write-to-file, + some minor changes to the motiongram-preview thing.

**Comment by aleksati** [comment]
Okay, so there seems to be no video-export-bugging in the build. I think we leave it for now, and if it causes more problems down line then we deal with it. However, there are some strange problems with the build-version on Mac. I will make another issue on this.

**Comment by balintlaczko** [comment]
Things seem to work well on Windows, but I will test some more with the build too.

**Comment by balintlaczko** [comment]
Seems to work with the build too.
