### ISSUE TITLE
Offline export issues on Mac build 

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#68]
Despite the max version working and exporting smoothly now, both with files and folder, the build version is behaving quite differently. When exporting in the Mac build, the framedumping doesn't seem to work. It sometimes registers a couple of frames before finishing, but mostly it doesn't dump any frames at all, exporting only the first frame. 

I suspect the problem is with the threading (after how it "looks" and behaves) but after probing the build in different ways I see that all scheduling is as it should be. So theoretically, everything is in order. Realtime playback also works fine in the build.

So something is occurring in the building process. I´ve checked that all abstractions, externals, and js.objects are included. Are there other things I can check/other operations that should be done before building? 

Also very interested in hearing how the Windows build for our current VideoAnalysis_with_abs patch is working.

**Comment by balintlaczko** [comment]
Ough, that doesn't sound good. Will look into this, while I make my Windows build, at the meantime you can maybe look at [this](https://cycling74.com/tutorials/advanced-max-standalones-part-1) tutorial series, I will do too, it may explain the issue somewhere along the way...

**Comment by aleksati** [comment]
Yes, I have seen those. I went through them again today. Same problem though.

More strange news: having the max console open in the build with integrated print objects seems to affect the behavior further. When having print objects after [Jit.qt.movie], for instance, the frames and jit.info might all print fine, but no video information is passed. Somehow. When these prints objects are there it takes longer for the application to process the videos than without, but the result is always the same. "The same" meaning the same type of bugging mentioned above.

I have tried:

- Probing the application build (with prints) to check whether the scheduling and threading is in order.
- Making builds from Max Project and regular Max Patch.
- Testing the app on different Macs and made builds with different Macs. (Macbook Pro and Mac Mini both with macOS High Sierra 10.13.6)
- Using avf and viddll engines. 
- Disabling overdrive from the Max menubar and [Standalone] object.
- Enabling cef, copy and gen support in [Standalone] object 
- Making a collective build. This is working fine, actually.

**Comment by balintlaczko** [comment]
The windows build seems to work exactly as the max patch. Will test it on more pc-s, but so far so good. There are little bugs surfacing here and there while using it, but nothing which would break the functionality (except the occasional [cv.jit.mean] artefacts - see #53 ) or which we can't iron out soon.
I built it after converting the patch into a project ("save as project") adding the *variable_descriptors.txt* which was not automatically detected, then hit build, and everything was fine.
I may appear optimistic, but let's wait for more testing experience! :P

**Comment by AleksanderTidemann** [comment]
Okay, that is good news! My hunch is that there was something funky with my "pull". or something like that.. I'll try to test it again before Thursday. If it's still bugging we can have a look together.

**Comment by AleksanderTidemann** [comment]
And now also this, in the new max update. Don't know if its the same for windows, but watch out.
https://cycling74.com/forums/max-8-1-2-problem-including-avf-engine-in-osx-stand-alone

**Comment by aleksati** [comment]
So I finally was able to make a build that works on OSX! I think the problem was that the build did not select the viddll videoengine, even if it was specified in the preferences and in jit.movie. I had to add a [;max videoengine viddll] message with a loadbang to make it work.

Now it seems to run smoothly.
