### ISSUE TITLE
Analysis bar should only work in framedump mode

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#7]
It is actually just getting the time values from the jit.qt.movie which is the same as the actual playbar.
I suggest that we only use it for the offline mode.

**Comment by alexarje** [comment]
Yes. This is a remainder from the old days.

**Comment by balintlaczko** [comment]
OK! I think it is still useful when doing the framedump, so let's keep it for that (it could also just be visible only while framedumping).

**Comment by alexarje** [comment]
Ah, I misunderstood your question. Yes, VideoAnalysis is primarily meant as a non-realtime tool, with the preview functionality being a "sub-feature". The other program AudioVideoAnalysis is optimized for realtime usage. So we need to ensure that VideoAnalysis works well for non-realtime use.

**Comment by aleksati** [comment]
This is implemented. Commit coming later, with @balintlaczko .
