### ISSUE TITLE
Wont (set $1) inhibits export-options in the menubar from going to export-sends? 

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#76]
@balintlaczko ,

When clicking export-options in menubar, the toggles UI are enabled with set $1 messages. That means there should not be no output going from the toggles to the individual sends beneath every export-option in UI. I'm I correct in this?

I guess I'm just curious on the thought process here.

**Comment by aleksati** [comment]
To clarify; it works fine(!), I'm just curious.

**Comment by aleksati** [comment]
Oh, I just saw that there were two patch chords from the [spray], one to the toggles, the other to the boxes. Nevermind this then.

**Comment by balintlaczko** [comment]
Yep, that's the trick to avoid infinite loops when you want to control the same value with 2 (or more) different UI elements (which also respect each other's state). So if you switch it on at point A, you can switch it off at point B, without having an infinite loop of A and B switching each other.
